name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    name: Create GH Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh release create ${{ github.ref_name }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
  build-and-upload:
    needs:
      - create-release
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: antdump
            asset_name: antdump-darwin-aarch64
          - os: macos-13
            target: x86_64-apple-darwin
            artifact_name: antdump
            asset_name: antdump-darwin-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: antdump.exe
            asset_name: antdump-windows-x86_64.exe
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: antdump
            asset_name: antdump-linux-aarch64
            cross: true
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: antdump
            asset_name: antdump-linux-x86_64
    runs-on: ${{ matrix.os }}
    name: release
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross compiler
        if: ${{ matrix.cross }}
        run: cargo install cross

      - run: cross build --release --target ${{ matrix.target }}
        if: ${{ matrix.cross }}

      - run: cargo build --release --target ${{ matrix.target }}
        if: ${{ !matrix.cross }}

      - name: Upload
        run: |
          cp ${{ matrix.artifact_name}} ${{ matrix.asset_name}}
          gh release upload ${{ github.ref_name }} ${{ matrix.asset_name}}
        working-directory: target/${{ matrix.target }}/release
        env:
          GH_TOKEN: ${{ github.token }}